import "./globals.css"
import "@rainbow-me/rainbowkit/styles.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { headers } from "next/headers"
import { type ReactNode } from "react"

import { Providers } from "./providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
}

export default async function RootLayout(props: { children: ReactNode }) {
  const cookie = (await headers()).get("cookie")
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers cookie={cookie}>{props.children}</Providers>
      </body>
    </html>
  )
}
